/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    courses: Course;
    posts: Post;
    testimonials: Testimonial;
    'team-members': TeamMember;
    'placement-partners': PlacementPartner;
    enquiries: Enquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'placement-partners': PlacementPartnersSelect<false> | PlacementPartnersSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'student-section-page': StudentSectionPage;
    'accreditation-page': AccreditationPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'student-section-page': StudentSectionPageSelect<false> | StudentSectionPageSelect<true>;
    'accreditation-page': AccreditationPageSelect<false> | AccreditationPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  sourceKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug: string;
  category: 'undergraduate' | 'diploma' | 'graduate';
  summary?: string | null;
  heroImage?: (number | null) | Media;
  thumbnail?: (number | null) | Media;
  rating?: number | null;
  /**
   * e.g. 5000+
   */
  students?: string | null;
  duration?: string | null;
  levels?: string | null;
  passPercentage?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. ACCA (UK) — shown in the course info strip
   */
  awardingBody?: string | null;
  /**
   * e.g. March / June / September / December
   */
  intake?: string | null;
  /**
   * Stat band shown below the hero, e.g. "170+ countries"
   */
  highlights?:
    | {
        icon?:
          | (
              | 'award'
              | 'shield'
              | 'teacher'
              | 'scholarship'
              | 'star'
              | 'users'
              | 'list'
              | 'percent'
              | 'globe'
              | 'monitor'
              | 'briefcase'
              | 'calendar'
              | 'clock'
              | 'layers'
              | 'book'
              | 'check'
            )
          | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * "Key benefits" card grid
   */
  benefits?:
    | {
        icon?:
          | (
              | 'award'
              | 'shield'
              | 'teacher'
              | 'scholarship'
              | 'star'
              | 'users'
              | 'list'
              | 'percent'
              | 'globe'
              | 'monitor'
              | 'briefcase'
              | 'calendar'
              | 'clock'
              | 'layers'
              | 'book'
              | 'check'
            )
          | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Programme papers grouped by level
   */
  curriculum?:
    | {
        levelTitle: string;
        levelSubtitle?: string | null;
        papers?:
          | {
              code: string;
              title: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  careerOpportunities?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  entryRequirements?:
    | {
        title: string;
        points?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Closing paragraph under entry requirements
   */
  entryNote?: string | null;
  faculty?: {
    description?: string | null;
    quote?: string | null;
    name?: string | null;
    title?: string | null;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  type: 'blog' | 'article' | 'event' | 'newsfeed';
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  publishedDate?: string | null;
  author?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  role?: string | null;
  rating?: number | null;
  message: string;
  avatar?: (number | null) | Media;
  group?: ('student' | 'alumni') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  group: 'board' | 'management' | 'faculty';
  image?: (number | null) | Media;
  socials?:
    | {
        platform?: ('facebook' | 'instagram' | 'linkedin') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement-partners".
 */
export interface PlacementPartner {
  id: number;
  name: string;
  logo: number | Media;
  url?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  type: 'contact' | 'book-seat' | 'enroll' | 'complaint';
  name: string;
  phone?: string | null;
  email?: string | null;
  subject?: string | null;
  course?: string | null;
  studentId?: string | null;
  message?: string | null;
  status?: ('new' | 'contacted' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'placement-partners';
        value: number | PlacementPartner;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  summary?: T;
  heroImage?: T;
  thumbnail?: T;
  rating?: T;
  students?: T;
  duration?: T;
  levels?: T;
  passPercentage?: T;
  content?: T;
  awardingBody?: T;
  intake?: T;
  highlights?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  curriculum?:
    | T
    | {
        levelTitle?: T;
        levelSubtitle?: T;
        papers?:
          | T
          | {
              code?: T;
              title?: T;
              id?: T;
            };
        id?: T;
      };
  careerOpportunities?:
    | T
    | {
        title?: T;
        id?: T;
      };
  entryRequirements?:
    | T
    | {
        title?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  entryNote?: T;
  faculty?:
    | T
    | {
        description?: T;
        quote?: T;
        name?: T;
        title?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  order?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  publishedDate?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  rating?: T;
  message?: T;
  avatar?: T;
  group?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  group?: T;
  image?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "placement-partners_select".
 */
export interface PlacementPartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  phone?: T;
  email?: T;
  subject?: T;
  course?: T;
  studentId?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  email?: string | null;
  phones?:
    | {
        number?: string | null;
        id?: string | null;
      }[]
    | null;
  address?: string | null;
  whatsapp?: string | null;
  socials?:
    | {
        platform?: ('facebook' | 'instagram' | 'whatsapp' | 'youtube' | 'linkedin' | 'tiktok') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  elearningLoginUrl?: string | null;
  elearningRegisterUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * YouTube video ID for the autoplaying hero background (optional — falls back to heroImage if blank)
   */
  heroVideoId?: string | null;
  heroCtaText?: string | null;
  heroCtaLink?: string | null;
  highlights?:
    | {
        /**
         * Icon name, e.g. award, shield, teacher, scholarship
         */
        icon?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  aboutTitle?: string | null;
  aboutText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  aboutImage?: (number | null) | Media;
  aboutStats?:
    | {
        label?: string | null;
        value?: number | null;
        id?: string | null;
      }[]
    | null;
  categories?:
    | {
        title?: string | null;
        icon?: string | null;
        courseCount?: number | null;
        id?: string | null;
      }[]
    | null;
  intakeLabel?: string | null;
  achievementTitle?: string | null;
  achievementText?: string | null;
  achievementVideoUrl?: string | null;
  achievementImage?: (number | null) | Media;
  sinceYear?: number | null;
  ctaTitle?: string | null;
  ctaText?: string | null;
  ctaImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  introTitle?: string | null;
  introText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  introImage?: (number | null) | Media;
  introStats?:
    | {
        label?: string | null;
        value?: number | null;
        id?: string | null;
      }[]
    | null;
  missionTitle?: string | null;
  missionText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  visionTitle?: string | null;
  visionText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  experienceYears?: string | null;
  tourImage?: (number | null) | Media;
  tourLabel?: string | null;
  tourVideoTitle?: string | null;
  tourVideoText?: string | null;
  /**
   * YouTube video ID for the College Tour popup video
   */
  tourVideoId?: string | null;
  chairmanMessageTitle?: string | null;
  chairmanMessageText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  chairmanImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  introTitle?: string | null;
  introAccent?: string | null;
  introText?: string | null;
  mapEmbedUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-section-page".
 */
export interface StudentSectionPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  worldRankPhotos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  nepalRankPhotos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  scholarshipPhotos?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accreditation-page".
 */
export interface AccreditationPage {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  items?:
    | {
        title: string;
        /**
         * Accent-colored part of the heading
         */
        highlight: string;
        /**
         * Blank line = new paragraph
         */
        description: string;
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  email?: T;
  phones?:
    | T
    | {
        number?: T;
        id?: T;
      };
  address?: T;
  whatsapp?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  elearningLoginUrl?: T;
  elearningRegisterUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroImage?: T;
  heroVideoId?: T;
  heroCtaText?: T;
  heroCtaLink?: T;
  highlights?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  aboutTitle?: T;
  aboutText?: T;
  aboutImage?: T;
  aboutStats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  categories?:
    | T
    | {
        title?: T;
        icon?: T;
        courseCount?: T;
        id?: T;
      };
  intakeLabel?: T;
  achievementTitle?: T;
  achievementText?: T;
  achievementVideoUrl?: T;
  achievementImage?: T;
  sinceYear?: T;
  ctaTitle?: T;
  ctaText?: T;
  ctaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  introTitle?: T;
  introText?: T;
  introImage?: T;
  introStats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  missionTitle?: T;
  missionText?: T;
  visionTitle?: T;
  visionText?: T;
  experienceYears?: T;
  tourImage?: T;
  tourLabel?: T;
  tourVideoTitle?: T;
  tourVideoText?: T;
  tourVideoId?: T;
  chairmanMessageTitle?: T;
  chairmanMessageText?: T;
  chairmanImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  introTitle?: T;
  introAccent?: T;
  introText?: T;
  mapEmbedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "student-section-page_select".
 */
export interface StudentSectionPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  worldRankPhotos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  nepalRankPhotos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  scholarshipPhotos?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accreditation-page_select".
 */
export interface AccreditationPageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  items?:
    | T
    | {
        title?: T;
        highlight?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}